export const INTERESTS = [
    'Accounting',
    'Africana Studies',
    'Animation',
    'Architecture',
    'Artificial Intelligence',
    'Behavioral Neuroscience',
    'Biochemistry',
    'Biology',
    'Biomechanics and Mechanobiology',
    'Biomedical Devices and Bioimaging',
    'Business Administration and Law',
    'Cell and Molecular Biology',
    'Cell and Tissue Engineering',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Communication Studies',
    'Computer Engineering',
    'Computing and Law',
    'Criminology and Criminal Justice',
    'Cultural Anthropology',
    'Cybersecurity',
    'Data Science',
    'Design',
    'Ecology and Marine Biology',
    'Economics',
    'Electrical Engineering',
    'English',
    'Entrepreneurship and Innovation',
    'Environmental and Sustainability Sciences',
    'Environmental Engineering',
    'Finance',
    'Fintech',
    'Foundations',
    'Game Design',
    'Health Science',
    'Healthcare Management and Consulting',
    'History',
    'Human-Centered Computing',
    'Human Services',
    'Industrial Engineering',
    'International Affairs',
    'International Business',
    'Journalism',
    'Languages, Literatures and Cultures',
    'Linguistics',
    'Management',
    'Management Information Systems',
    'Marketing',
    'Mathematics',
    'Mechanical Engineering',
    'Media and Arts Management',
    'Media and Screen Studies',
    'Music',
    'Music Industry',
    'Music Technology',
    'Nursing',
    'Performance and Extended Realities',
    'Pharmacy',
    'Philosophy',
    'Photography',
    'Physical Therapy',
    'Physics',
    'Political Science',
    'Product Management',
    'Psychology',
    'Public Health',
    'Public Policy',
    'Sociology',
    'Software',
    'Speech-Language Pathology and Audiology',
    'Studio Art',
    'Supply Chain Management',
    'Systems',
    'Systems, Synthetic, and Computational Bioengineering',
    'Theatre',
    'Video Arts',
] as const;

const INTEREST_SET: ReadonlySet<string> = new Set(INTERESTS);

export const isInterest = (value: unknown): boolean => typeof value === 'string' && INTEREST_SET.has(value);
