export const INTERESTS = [
    'Accounting',
    'Accounting and Advisory Services',
    'Africana Studies',
    'Applied Physics',
    'Architecture',
    'Artificial Intelligence',
    'Behavioral Neuroscience',
    'Biochemistry',
    'Bioengineering',
    'Biology',
    'Brand Management',
    'Business Administration',
    'Business Administration and Law',
    'Business Analytics',
    'Cell and Molecular Biology',
    'Chemical Engineering',
    'Chemistry',
    'Civil Engineering',
    'Communication Studies',
    'Computer Engineering',
    'Computer Science',
    'Computing and Law',
    'Corporate Innovation',
    'Criminology and Criminal Justice',
    'Cultural Anthropology',
    'Cybersecurity',
    'Data Science',
    'Design',
    'Ecology and Evolutionary Biology',
    'Economics',
    'Electrical Engineering',
    'English',
    'Entrepreneurial Startups',
    'Environmental and Sustainability Sciences',
    'Environmental Engineering',
    'Fashion Marketing',
    'Finance',
    'Fintech',
    'Foundations (CS theory)',
    'Game Design',
    'Global Business and Strategy',
    'Health Science',
    'Healthcare Management and Consulting',
    'History',
    'Human-Centered Computing',
    'Human Services',
    'Industrial Engineering',
    'International Affairs',
    'International Business',
    'Investment Banking',
    'Investments',
    'Journalism',
    'Landscape Architecture',
    'Languages, Literatures and Cultures',
    'Linguistics',
    'Management',
    'Management Information Systems',
    'Marine Biology',
    'Marketing',
    'Marketing Analytics',
    'Mathematics',
    'Mechanical Engineering',
    'Media and Arts Management',
    'Media and Screen Studies',
    'Media Arts',
    'Music',
    'Music Composition and Songwriting',
    'Music Industry',
    'Music Technology',
    'Nursing',
    'Performance and Extended Realities',
    'Pharmaceutical Sciences',
    'Pharmacy (PharmD)',
    'Philosophy',
    'Physical Therapy (DPT)',
    'Physics',
    'Political Science',
    'Product Management',
    'Psychology',
    'Public Health',
    'Public Policy',
    'Quantitative Finance',
    'Social Innovation and Entrepreneurship',
    'Sociology',
    'Software',
    'Speech-Language Pathology and Audiology',
    'Studio Art',
    'Supply Chain Management',
    'Systems',
    'Theatre',
] as const;

const INTEREST_SET: ReadonlySet<string> = new Set(INTERESTS);

export const isInterest = (value: unknown): boolean => typeof value === 'string' && INTEREST_SET.has(value);
